name: Continuous integration
on: [push]

jobs:
  lint:
    name: "Code quality checks"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone the repository"
        uses: actions/checkout@v1
      - name: "Use Node 12.x"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: "Install dependencies"
        working-directory: ./api
        run: yarn install
      - name: "Run linter"
        working-directory: ./api
        run: yarn run lint
